<a href="https://colab.research.google.com/github/nikitaguptaa/Python-Playground/blob/main/1_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# creating single dimensional array then use array() , it is in built function of numpy.
A=np.array([67,89,56,60,45,66])

In [3]:
print(A)

[67 89 56 60 45 66]


In [4]:
type(A)

numpy.ndarray

In [5]:
# shows the type of dimensional
A.ndim

1

In [6]:
# (row,col) means here is 6 rows and 1 column.
A.shape

(6,)

In [7]:
# Shows type of element inside
A.dtype

dtype('int64')

In [8]:
A=np.array([23,34,45.6,56,45])

In [9]:
print(A)

[23.  34.  45.6 56.  45. ]


In [10]:
A.dtype

dtype('float64')

In [11]:
A=np.array([23,34,45.5,45.3,45,56],int)

In [12]:
print(A)

[23 34 45 45 45 56]


In [13]:
A.dtype

dtype('int64')

In [14]:
A.shape

(6,)

In [15]:
# no. of elements
A.size

6

In [17]:
# no. of bytes in each element
A.itemsize

8

In [18]:
A.nbytes

48

In [19]:
# access element with the help of index
# Access element at fourth position
A[3]

np.int64(45)

In [20]:
A[-1]

np.int64(56)

In [21]:
# Access element through slicing
A[2:5]

array([45, 45, 45])

In [23]:
A[[1,2,3]]

array([34, 45, 45])

In [24]:
A[0:7:2]

array([23, 45, 45])

In [25]:
A[:5]

array([23, 34, 45, 45, 45])

In [26]:
#sum of all elements
A.sum()

np.int64(248)

In [27]:
# to find the mean value
A.mean()

np.float64(41.333333333333336)

In [28]:
# to find the maximum value in numPy array
A.max()

np.int64(56)

In [29]:
# to find the minimum value in numPy array
A.min()

np.int64(23)

In [30]:
A=np.array([[23,34,45,65],[78,65,45,34],[98,76,56,45]])

In [31]:
print(A)

[[23 34 45 65]
 [78 65 45 34]
 [98 76 56 45]]


In [32]:
#Access Value using a. indexing  b. slicing
#a.indexing
A[1,2]

np.int64(45)

In [33]:
A[-2,-3]

np.int64(65)

In [34]:
A[0:,:]

array([[23, 34, 45, 65],
       [78, 65, 45, 34],
       [98, 76, 56, 45]])

In [35]:
#rowwise sum
A.sum(axis=1)

array([167, 222, 275])

In [36]:
#columnwise sum
A.sum(axis=0)

array([199, 175, 146, 144])

In [38]:
#transpose means row into column and column into row
A.transpose()

array([[23, 78, 98],
       [34, 65, 76],
       [45, 45, 56],
       [65, 34, 45]])

In [39]:
#flatten means convert two dimensional array into single dimensional array
A.flatten()

array([23, 34, 45, 65, 78, 65, 45, 34, 98, 76, 56, 45])

In [40]:
#zeros and ones --> single dimensional array
Z=np.zeros(4) # 4 is rows and default data type will be float
print(Z)

[0. 0. 0. 0.]


In [41]:
#5 is row and default data type will be float
X=np.ones(5)
print(X)

[1. 1. 1. 1. 1.]


In [44]:
#Zeros (()) --> to create two dimensional array

Z=np.zeros((3,4))   #3 is row and 4 is column by default data type float
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
Z=np.zeros((3,4),int)   #3 is row and 4 is column
print(Z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [46]:
#ones (()) --> to create two dimensional array
A=np.ones((3,4))       #3 is row and 4 is column by default data type float
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
#create identity  matrix then use inbuilt function eye() ,, default data type float
I=np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [48]:
#fill() inbuilt function of numpy
A=np.array([2,3,5],float)
print(A)

[2. 3. 5.]


In [49]:
A.fill(A.mean())
print(A)

[3.33333333 3.33333333 3.33333333]


In [50]:
#another way to create array is arange() is inbuilt function of numPy array
#syntax : np.arange(Start,Stop,Step)
#create a single dimensional array

A=np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
B=np.arange(2,21)
print(B)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [52]:
A=np.arange(0,21,1)    #start,stop,step
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [54]:
A=np.arange(10,20)
print(A)

[10 11 12 13 14 15 16 17 18 19]


In [55]:
A.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
#another way to create array

A=np.array(range(20))     #by default data type int
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [57]:
A=np.array(range(10),float)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [58]:
#we can change a dimension with the help of reshape()
A=A.reshape(2,5)
print(A)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [60]:
#use 'in' to search item in array
5 in A

True

In [61]:
print(A<50) # binary index

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [62]:
#accessing those value which less than 50
A[A<50]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
#mathematical function of numPy
#Trigonometry function sin() , cos() , tan()

y=np.sin(np.radians(30))

In [65]:
y

np.float64(0.49999999999999994)

In [66]:
np.round(y,1)

np.float64(0.5)

In [67]:
#log base will be by default 2
np.log(1)

np.float64(0.0)

In [69]:
np.log10(10)

np.float64(1.0)

In [70]:
np.sqrt(4)

np.float64(2.0)